#!/usr/bin/perl
# Author: Marcos Pletcher
# I/O

use strict;
use warnings;
 
my $filereport = 'report.txt'; # creates my file
open(my $var, '>', $filereport) or die "The system cannot open the file '$filereport' $!"; # Die function raises an exception
print $var "My first report generated by perl\n"; # writes my message
close $var;
print "done\n";

__END__ 